config/routes.rb
Kairos::Application.routes.draw do

  
  
  match "/" => "application#index", :as => :application, via: [:get,:post]
  
  resources :activities
  match 'calendar', to: 'activities#calendar', as: :calendar, via: [:get, :post]
  
  resources :leaves
  match "submit_leaves" => "leaves#submit_leaves", :via => [:put]
  match "cancel_leave" => 'leaves#cancel_leave', :via => [:put]
  
  resources :person_tasks do
    collection do
      put 'submit_tasks'
    end
  end
    
  resources :people
  resources :rights
  resources :events
  
  match "submit_events" => "events#submit_events", :via => [:put]
  match "remove_person" => 'events#remove_person', :via => [:put]
  match "add_people" => 'events#add_people', :via => [:put]
  
  match 'login', to: 'login#login', as: :login ,via: [:get, :post]
  match 'logout', to: 'login#logout', as: :logout, via: [:get, :post]
  match 'dashboard', to: 'person_tasks#dashboard', as: :dashboard, via: [:get, :post]
  match "has_seen" => 'activities#has_seen', :via => [:put]
  
  match 'set_date', to: 'login#set_date', as: :set_date , via: [:get, :post]
  match "submit_tasks" => "person_tasks#submit_tasks", :via => [:put]
  match "get_tasks_assignments" => 'tasks#get_tasks_assignments', :via => [:get]
  match "create_role_task" => 'tasks#create_role_task', :via => [:post]
  match "deactivate_role_task" => 'tasks#deactivate_role_task', :via => [:put]
  match "activate_role_task" => 'tasks#activate_role_task', :via => [:put]
  
  resources :tasks
  
  match "tasks_report" => 'reports#tasks_report', :via => [:get,:post]
  match "utilization_rates" => 'reports#utilization_rates', :via => [:get,:post]
  match "search_tasks" => 'reports#search_tasks', :via => [:get,:post]
  match "search_rates" => 'reports#search_rates', :via => [:get,:post]
  
  match "add_tasks_to_role" => "manage#add_tasks_to_role", :via => [:get, :post]
  match "get_specific_tasks_assignments" => 'specific_tasks#get_specific_tasks_assignments', :via => [:get]
  match "get_role_task" => 'specific_tasks#get_role_task', :via => [:get]
  match "create_specific_role_task" => 'specific_tasks#create_specific_role_task', :via => [:post]
  
  resources :specific_tasks
  match "deactivate_role_specific_task" => 'specific_tasks#deactivate_role_specific_task', :via => [:put]
  match "activate_role_specific_task" => 'specific_tasks#activate_role_specific_task', :via => [:put]
  
  match "tasks_approval" => 'approvals#tasks_approval', :via => [:get,:post]
  match "leaves_approval" => 'approvals#leaves_approval', :via => [:get,:post]
  
  match "approve_tasks" => 'approvals#approve_tasks', :via => [:put]
  match "disapprove_tasks" => 'approvals#disapprove_tasks', :via => [:put]
  
  match "approve_leaves" => 'approvals#approve_leaves', :via => [:put]
  match "disapprove_leaves" => 'approvals#disapprove_leaves', :via => [:put]
  
  match "end_task" => 'person_tasks#end_task', :via => [:put]
  match "generate_spreadsheets" => "reports#generate_spreadsheets", :as => :generate_spreadsheets, :via => [:get, :post]
  
end

app/controllers/approvals_controller.rb
class ApprovalsController < ApplicationController
  require 'will_paginate/array'
 
  before_filter :authorize
  
  def tasks_approval
    session[:person] = params[:person]
    @for_approvals = PersonTask.find_tasks_to_be_approved(params[:person],[:task,:specific_task,{:person => [:department, :organization] }],current_user)
    @total_count = @for_approvals.length 
    @for_approvals = @for_approvals.paginate(:page => params[:page],:per_page => 100)
  end
  
  def approve_tasks
    PersonTask.approve_tasks(params[:p_tasks],current_user)
    flash[:notice] = 'Process completed by' + " " + current_user.first_name + " " + current_user.last_name 

    @for_approvals = PersonTask.find_tasks_to_be_approved(session[:person],[:task,:specific_task,{:person => [:department, :organization] }],current_user)
    @total_count = @for_approvals.length 
    @for_approvals = @for_approvals.paginate(:page => params[:page],:per_page => 100)
  end
  
  def disapprove_tasks
    PersonTask.disapprove_tasks(params[:p_tasks],current_user)
    flash[:notice] = 'Proccess completed by' + " " + current_user.first_name + " " + current_user.last_name 

    @for_approvals = PersonTask.find_tasks_to_be_approved(session[:person],[:task,:specific_task,{:person => [:department, :organization] }],current_user)
    @total_count = @for_approvals.length 
    @for_approvals = @for_approvals.paginate(:page => params[:page],:per_page => 100)
  end
  
  def leaves_approval
    @for_approvals = Leave.find_leaves_to_be_approved({:person => [:department, :organization]},current_user)
    @total_count = @for_approvals.length 
    @for_approvals = @for_approvals.paginate(:page => params[:page],:per_page => 100)
  end
  
  def approve_leaves
    @leaves = Leave.where(:id => params[:leaves])
    
    Leave.approve_leaves(@leaves,current_user)
    
    people_ids = @leaves.map {|p| p.person_id}.join(",")  
    @people = Person.where(:id => people_ids.split(','))
    
    for leave in @leaves
      for person in @people
        if leave.person_id == person.id 
          KairosMailer.approve_leave(person,current_user,leave).deliver        
          leave.create_activity :approve_leaves, owner: current_user, recipient: person, date: leave.date
        end  
      end
    end  
    
    @for_approvals = Leave.find_leaves_to_be_approved({:person => [:department, :organization]},current_user)
    @total_count = @for_approvals.length 
    @for_approvals = @for_approvals.paginate(:page => params[:page],:per_page => 100)
    
    flash[:notice] = 'Process completed by' + " " + current_user.first_name + " " + current_user.last_name 
    
  end
  
  def disapprove_leaves
     @leaves = Leave.where(:id => params[:leaves])

      Leave.disapprove_leaves(@leaves,current_user)

      people_ids = @leaves.map {|p| p.person_id}.join(",")  
      @people = Person.where(:id => people_ids.split(','))

      for leave in @leaves
        for person in @people
          if leave.person_id == person.id 
            KairosMailer.disapprove_leave(person,current_user,leave).deliver        
            leave.create_activity :disapprove_leaves, owner: current_user, recipient: person, date: leave.date
          end  
        end
      end

    @for_approvals = Leave.find_leaves_to_be_approved({:person => [:department, :organization]},current_user)
    @total_count = @for_approvals.length 
    @for_approvals = @for_approvals.paginate(:page => params[:page],:per_page => 100)
    
    flash[:notice] = 'Proccess completed by' + " " + current_user.first_name + " " + current_user.last_name 
    
  end
end  

app/views/approvals/_count.html.erb
<font style='color:red'><b><%="#{@total_count}" %></font> submitted for approval</b>	

app/views/approvals/_js.html.erb
<script>
  $(document).ready(function() {	  
    $("#approve").click(function(){
	  
	  var arr = new Array();
	  $('#for_cbox input[type="checkbox"]:checked').each(function() {
	    arr.push($(this).val());
	  });

	  if(arr.length === 0){
		$('#approve_modal').modal();
		$('.modal-body').html("Nothing selected!");
		$('#approve_link').hide();
		return false;
	  } 
	  else{
		$('#approve_modal').modal();
		$('.modal-body').html("Are you sure you want to approve selected?");
		$('#approve_link').show();
	  } 
    });	
    
    $("#approve_link").click(function(){
      dataString = $("#tasks").serialize();
	  $.ajax({
	    type: "PUT",
		dataType: "script",
		url: "approve_tasks",
		data: dataString,
		  beforeSend: function(data)
		  {
		    $('#spin_spin').show();	   
		  },
		  success: function(response)
		  {
		    $('#spin_spin').hide();	
		  }
	   });
	   $('#approve_modal').modal('toggle')  
	   return false;
	 });
 
	 $("#disapprove").click(function(){
		  var arr = new Array();
		  $('#for_cbox input[type="checkbox"]:checked').each(function() {
		    arr.push($(this).val());
		  });

		  if(arr.length === 0){
			$('#disapprove_modal').modal();
			$('.modal-body').html("Nothing selected!");
			$('#disapprove_link').hide();
			return false;
		  } 
		  else{
			$('#disapprove_modal').modal();
			$('.modal-body').html("Are you sure you want to disapprove selected?");
			$('#disapprove_link').show();
		  } 
	    });	

	    $("#disapprove_link").click(function(){
	      dataString = $("#tasks").serialize();
		  $.ajax({
		    type: "PUT",
			dataType: "script",
			url: "disapprove_tasks",
			data: dataString,
			  beforeSend: function(data)
			  {
			    $('#spin_spin').show();	   
			  },
			  success: function(response)
			  {
			    $('#spin_spin').hide();	
			  }
		   });
		   $('#disapprove_modal').modal('toggle')  
		   return false;
		 });   

	$("#approval_search select").change(function(){
      dataString = $("#approval_search").serialize();
	  $.ajax({
	    type: "GET",
		dataType: "script",
		url: "/tasks_approval",
		data: dataString,
		  beforeSend: function(data)
		  {
		    $('#spin_spin').show();
		  },
		  success: function(response)
		  {
		    $('#spin_spin').hide();	
		  }

	   });

	   return false;
    });
    
	$('#approve').popover(
	  {
	     trigger: 'hover',
	     html: true,
	     placement: 'right',
	     content: 'This button will process the approval of each selected tasks.'
	  });
    
    $('#disapprove').popover(
	  {
	     trigger: 'hover',
	     html: true,
	     placement: 'left',
	     content: 'This button will process the disapproval of each selected tasks.'
	  });

  });
</script>

app/views/approvals/_leaves_js.html.erb
<script>
  $(document).ready(function() {	  
    $("#approve").click(function(){
	  
	  var arr = new Array();
	  $('#for_cbox input[type="checkbox"]:checked').each(function() {
	    arr.push($(this).val());
	  });

	  if(arr.length === 0){
		$('#approve_modal').modal();
		$('.modal-body').html("Nothing selected!");
		$('#approve_link').hide();
		return false;
	  } 
	  else{
		$('#approve_modal').modal();
		$('.modal-body').html("Are you sure you want to approve selected?");
		$('#approve_link').show();
		return false
	  } 
    });
    
    $("#approve_link").click(function(){
      dataString = $("#leaves").serialize();
	  $.ajax({type: "PUT",dataType: "script",url: "approve_leaves",
		data: dataString,
		  beforeSend: function(data)
		  {
		    $('#spin_spin').show();	   
		  },
		  success: function(response)
		  {
		    $('#spin_spin').hide();	
		  }
	   });
	   $('#approve_modal').modal('toggle')  
	   return false;
	 });
 
	 $("#disapprove").click(function(){
		  var arr = new Array();
		  $('#for_cbox input[type="checkbox"]:checked').each(function() {
		    arr.push($(this).val());
		  });

		  if(arr.length === 0){
			$('#disapprove_modal').modal();
			$('.modal-body').html("Nothing selected!");
			$('#disapprove_link').hide();
			return false;
		  } 
		  else{
			$('#disapprove_modal').modal();
			$('.modal-body').html("Are you sure you want to disapprove selected?");
			$('#disapprove_link').show();
			return false;
		  } 
	    });	

	    $("#disapprove_link").click(function(){
	      dataString = $("#leaves").serialize();
		  $.ajax({type: "PUT",dataType: "script",url: "disapprove_leaves",
			 data: dataString,
			  beforeSend: function(data)
			  {
			    $('#spin_spin').show();	   
			  },
			  success: function(response)
			  {
			    $('#spin_spin').hide();	
			  }
		   });
		   $('#disapprove_modal').modal('toggle')  
		   return false;
		 });   

	$("#approval_search select").change(function(){
      dataString = $("#approval_search").serialize();
	  $.ajax({type: "GET",dataType: "script",url: "/leaves_approval",
		data: dataString,
		  beforeSend: function(data)
		  {
		    $('#spin_spin').show();
		  },
		  success: function(response)
		  {
		    $('#spin_spin').hide();	
		  }
	   });

	   return false;
    });
    
	$('#approve').popover(
	  {
	     trigger: 'hover',
	     html: true,
	     placement: 'right',
	     content: 'This button will process the approval of each selected leaves.'
	  });
    
    $('#disapprove').popover(
	  {
	     trigger: 'hover',
	     html: true,
	     placement: 'left',
	     content: 'This button will process the disapproval of each selected leaves.'
	  });

  });
</script>

app/views/approvals/_leaves_to_be_approved.html.erb
<% if @for_approvals %>

<br/>

<div class='pull-right' style='margin-top:-80px;margin-right:-100px'>
  <%= will_paginate @for_approvals %>
</div>

<br><br/>

<br/>
<%= form_tag approve_tasks_url,:method => :post, :id => 'leaves' do %> 
<table class="table table-striped" id='for_cbox'>
  <thead>
    <tr>
	  <th><%= check_box_tag("master",1,false,{ :id => "select_all", :onclick => "toggleItems(this,'leaves')" }) %></th>	
      <th>Date</th>
      <th>Person</th>
      <th>Leave Type</th>
      <th>Reason</th>
	  <th>Disapproved by</th>
    </tr>
  </thead>
  <tbody>
    <% for leave in @for_approvals %>
    
       <% if leave.is_submitted? %><tr class='warning'> <% end %>
	   <% if leave.is_approved? %><tr class='success'> <% end %>
	   <% if leave.is_disapproved? %><tr class='error'> <% end %>
		
		<td><%= check_box_tag("leaves[]",leave.id,false,{ :class => "leaves"}) %></td>
		<td><%= leave.date.strftime('%b. %e, %Y') %></td>
		<td><%= leave.person.name %></td>
        <td><%= leave.leave_type.name %></td>
        <td><%= leave.reason %></td>
        <td>
	        <%= leave.approved? if leave.is_disapproved?  %>
		</td>

       
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<div class='pull-right' >
  <%= will_paginate @for_approvals %>
</div>

<% end %>

app/views/approvals/_to_be_approved.html.erb
<% if @for_approvals %>

<br/>

<div class='pull-right' style='margin-top:-80px;margin-right:-100px'>
  <%= will_paginate @for_approvals %>
</div>

<br><br/>

<br/>
<%= form_tag approve_tasks_url,:method => :post, :id => 'tasks' do %> 
<table class="table table-striped" id='for_cbox'>
  <thead>
    <tr>
	  <th><%= check_box_tag("master",1,false,{ :id => "select_all", :onclick => "toggleItems(this,'activities')" }) %></th>	
      <th width='10%'>Shift Date</th>
      <th>Person</th>
      <th  width='15%'>Primary Task</th>
      <th  width='15%'>Specific Task</th>
      <th width='9%'>Start Time</th>
      <th width='9%'>End Time</th>
      <th width='9%'>Total Time</th>
      <th  width='10%'>From or To</th>
	  <th width='10%'>Note</th>
   
    </tr>
  </thead>
  <tbody>
    <% for person_task in @for_approvals %>
    
       <% if person_task.is_submitted? %><tr class='warning'> <% end %>
	   <% if person_task.is_approved? %><tr class='success'> <% end %>
	   <% if person_task.is_disapproved? %><tr class='error'> <% end %>
		
		<td><%= check_box_tag("p_tasks[]",person_task.id,false,{ :class => "activities"}) %></td>
		<td><%= person_task.start.strftime('%b. %e, %Y') if !person_task.start.nil? %></td>
		<td><%= person_task.person.first_name %></td>
        <td><%= person_task.task.name if !person_task.task_id.nil? %></td>
        <td><%= person_task.specific_task.name if !person_task.specific_task_id.nil? %></td>
        <td><%= person_task.start.strftime('%l:%M:%S %p') if !person_task.start.nil? %></td>
        <td><%= person_task.end.strftime('%l:%M:%S %p') if !person_task.end.nil? %></td>
		<td><%= person_task.total_time.strftime('%H:%M:%S') if !person_task.total_time.nil? %></td>
		<td><%= person_task.person_in_charge %></td>
		<td><%= person_task.note %></td>

       
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<div class='pull-right' >
  <%= will_paginate @for_approvals %>
</div>

<% end %>

app/views/approvals/approve_leaves.js.erb
$('#for_approval').html("<%= escape_javascript(render("leaves_to_be_approved")) %>");
$('#count').html("<%= escape_javascript(render("count")) %>");
<%= flash_notice(flash.first[1], flash.first[0]) unless flash.blank? %>

app/views/approvals/approve_tasks.js.erb
$('#for_approval').html("<%= escape_javascript(render("to_be_approved")) %>");
$('#count').html("<%= escape_javascript(render("count")) %>");
<%= flash_notice(flash.first[1], flash.first[0]) unless flash.blank? %>

app/views/approvals/disapprove_leaves.js.erb
$('#for_approval').html("<%= escape_javascript(render("leaves_to_be_approved")) %>");
$('#count').html("<%= escape_javascript(render("count")) %>");
<%= flash_notice(flash.first[1], flash.first[0]) unless flash.blank? %>

app/views/approvals/disapprove_tasks.js.erb
$('#for_approval').html("<%= escape_javascript(render("to_be_approved")) %>");
$('#count').html("<%= escape_javascript(render("count")) %>");
<%= flash_notice(flash.first[1], flash.first[0]) unless flash.blank? %>

app/views/approvals/leaves_approval.html.erb
<%= render partial: 'leaves_js' %>

<div class="span12 body_layout" >
	<div class='own_page_header'>	
	   <h3>Leave Approval</h3>
	   <div style='margin-top:-15px'>
	     <p>approve or reject a leave<p>
		 <div id='count'>
 		   <%= render partial: 'count' %>
	     </div>
	   </div>
	
	   <div id='spin_spin' class='pull-right' style='display:none;margin-top:-100px'>
	     <%= image_tag 'spin.gif' %>
	   </div>
	</div>
  <div style='padding:20px'>
	
  <br/>
 
  <div id="approve_modal" class="modal hide fade in" style="display: none; ">  
    <div class="modal-header">  
      <a class="close" data-dismiss="modal">×</a>  
      <font style='color:green'><h4>Approve Leave!</h4></font>  
    </div>  
    <div class="modal-body">   
      <p>Are you sure you want to approve selected?</p>                
    </div>  
    <div class="modal-footer">  
      <a href="#" class="btn btn-success" id='approve_link'>Approve</a>  
      <a href="#" class="btn" data-dismiss="modal">Cancel</a>  
    </div>  
  </div> 

  <div id="disapprove_modal" class="modal hide fade in" style="display: none; ">  
    <div class="modal-header">  
      <a class="close" data-dismiss="modal">×</a>  
      <font style='color:red'><h4>Disapprove Leave!</h4> </font> 
    </div>  
    <div class="modal-body">   
      <p>Are you sure you want to approve selected?</p>                
    </div>  
    <div class="modal-footer">  
      <a href="#" class="btn btn-danger" id='disapprove_link'>Disapprove</a>  
      <a href="#" class="btn" data-dismiss="modal">Cancel</a>  
    </div>  
  </div> 
	


	<div id = 'approve' class='btn btn-success pull-left' style='margin-right:120px' >Approve</div>
	<div id = 'disapprove' class='btn btn-danger pull-right' >Disapprove</div>
	
	<div id='for_approval'>
	  <%= render partial: 'leaves_to_be_approved' %>
	</div>
	
  </div>
</div>

app/views/approvals/tasks_approval.html.erb
<%= render partial: 'js' %>

<div class="span12 body_layout" >
	<div class='own_page_header'>	
	   <h3>Tasks Approval</h3>
	   <div style='margin-top:-15px'>
	     <p>approve or reject a tasks<p>
		 <div id='count'>
 		   <%= render partial: 'count' %>
	     </div>
	   </div>
	
	   <div id='spin_spin' class='pull-right' style='display:none;margin-top:-100px'>
	     <%= image_tag 'spin.gif' %>
	   </div>
	</div>
  <div style='padding:20px'>
	
  <br/>
 
  <div id="approve_modal" class="modal hide fade in" style="display: none; ">  
    <div class="modal-header">  
      <a class="close" data-dismiss="modal">×</a>  
      <font style='color:green'><h4>Approve Tasks!</h4></font>  
    </div>  
    <div class="modal-body">   
      <p>Are you sure you want to approve selected?</p>                
    </div>  
    <div class="modal-footer">  
      <a href="#" class="btn btn-success" id='approve_link'>Approve</a>  
      <a href="#" class="btn" data-dismiss="modal">Cancel</a>  
    </div>  
  </div> 

  <div id="disapprove_modal" class="modal hide fade in" style="display: none; ">  
    <div class="modal-header">  
      <a class="close" data-dismiss="modal">×</a>  
      <font style='color:red'><h4>Disapprove Tasks!</h4> </font> 
    </div>  
    <div class="modal-body">   
      <p>Are you sure you want to approve selected?</p>                
    </div>  
    <div class="modal-footer">  
      <a href="#" class="btn btn-danger" id='disapprove_link'>Disapprove</a>  
      <a href="#" class="btn" data-dismiss="modal">Cancel</a>  
    </div>  
  </div> 
	
	<%= form_tag tasks_approval_path, :method => 'get', :id => 'approval_search', :class => "form-search " do %><div class='pull-left' style='margin-left: 0px'>
	  <label>Employee Name</label>
	  <%= select_tag("person", options_from_collection_for_select(options_for_employees, :id, :first_name ,""), :include_blank => true) %>
	</div>   <% end %>
	<br/><br/>

	<div id = 'approve' class='btn btn-success pull-left' style='margin-right:120px' >Approve</div>
	<div id = 'disapprove' class='btn btn-danger pull-right' >Disapprove</div>
	
	<div id='for_approval'>
	  <%= render partial: 'to_be_approved' %>
	</div>
	

  </div>
</div>	

app/views/approvals/tasks_approval.js.erb
$('#for_approval').html("<%= escape_javascript(render("to_be_approved")) %>");
$('#count').html("<%= escape_javascript(render("count")) %>");