config/routes.rb
Kairos::Application.routes.draw do

  
  
  match "/" => "application#index", :as => :application, via: [:get,:post]
  
  resources :activities
  match 'calendar', to: 'activities#calendar', as: :calendar, via: [:get, :post]
  
  resources :leaves
  match "submit_leaves" => "leaves#submit_leaves", :via => [:put]
  match "cancel_leave" => 'leaves#cancel_leave', :via => [:put]
  
  resources :person_tasks do
    collection do
      put 'submit_tasks'
    end
  end
    
  resources :people
  resources :rights
  resources :events
  
  match "submit_events" => "events#submit_events", :via => [:put]
  match "remove_person" => 'events#remove_person', :via => [:put]
  match "add_people" => 'events#add_people', :via => [:put]
  
  match 'login', to: 'login#login', as: :login ,via: [:get, :post]
  match 'logout', to: 'login#logout', as: :logout, via: [:get, :post]
  match 'dashboard', to: 'person_tasks#dashboard', as: :dashboard, via: [:get, :post]
  match "has_seen" => 'activities#has_seen', :via => [:put]
  
  match 'set_date', to: 'login#set_date', as: :set_date , via: [:get, :post]
  match "submit_tasks" => "person_tasks#submit_tasks", :via => [:put]
  match "get_tasks_assignments" => 'tasks#get_tasks_assignments', :via => [:get]
  match "create_role_task" => 'tasks#create_role_task', :via => [:post]
  match "deactivate_role_task" => 'tasks#deactivate_role_task', :via => [:put]
  match "activate_role_task" => 'tasks#activate_role_task', :via => [:put]
  
  resources :tasks
  
  match "tasks_report" => 'reports#tasks_report', :via => [:get,:post]
  match "utilization_rates" => 'reports#utilization_rates', :via => [:get,:post]
  match "search_tasks" => 'reports#search_tasks', :via => [:get,:post]
  match "search_rates" => 'reports#search_rates', :via => [:get,:post]
  
  match "add_tasks_to_role" => "manage#add_tasks_to_role", :via => [:get, :post]
  match "get_specific_tasks_assignments" => 'specific_tasks#get_specific_tasks_assignments', :via => [:get]
  match "get_role_task" => 'specific_tasks#get_role_task', :via => [:get]
  match "create_specific_role_task" => 'specific_tasks#create_specific_role_task', :via => [:post]
  
  resources :specific_tasks
  match "deactivate_role_specific_task" => 'specific_tasks#deactivate_role_specific_task', :via => [:put]
  match "activate_role_specific_task" => 'specific_tasks#activate_role_specific_task', :via => [:put]
  
  match "tasks_approval" => 'approvals#tasks_approval', :via => [:get,:post]
  match "leaves_approval" => 'approvals#leaves_approval', :via => [:get,:post]
  
  match "approve_tasks" => 'approvals#approve_tasks', :via => [:put]
  match "disapprove_tasks" => 'approvals#disapprove_tasks', :via => [:put]
  
  match "approve_leaves" => 'approvals#approve_leaves', :via => [:put]
  match "disapprove_leaves" => 'approvals#disapprove_leaves', :via => [:put]
  
  match "end_task" => 'person_tasks#end_task', :via => [:put]
  match "generate_spreadsheets" => "reports#generate_spreadsheets", :as => :generate_spreadsheets, :via => [:get, :post]
  
end

app/models/event.rb
class Event < ActiveRecord::Base
  include PublicActivity::Common
  
  belongs_to :creator, :class_name => "Person", :foreign_key => "created_by"
  
  
  validates_presence_of :description, :from, :to
  
end  

app/controllers/events_controller.rb
class EventsController < ApplicationController
   before_filter :authorize
  def index
    @events = Event.all
    
    respond_to do |format|
      format.html {}
    end 
  end
  
  def show
    @event = Event.find(params[:id])
    ids = @event.event_people
    @added_people = Person.where(:id => ids.split(','))
    @people = Person.where.not(id: ids.split(','))
  end  
  
  def new
    @event = Event.new
  end
  
  def edit
    @event = Event.find(params[:id])
  end
  
  def create
    @event = Event.new(event_params)
    @event.created_by = current_user.id
    @event.event_people = current_user.id
    
    respond_to do |format|
      if @event.save
        
        dt1 = @event.from.to_date
        dt2 = @event.to.to_date
        
        days_ctr = dt2 - dt1
        event_date = @event.from
        i = 1
        if days_ctr.to_i > 1
          days_ctr.to_i.times do
            @event.create_activity :submit_events, owner: current_user, date: event_date 
            event_date = event_date + 1.day
          end
          @event.create_activity :submit_events, owner: current_user, date: @event.to 
        elsif days_ctr.to_i == 1
          @event.create_activity :submit_events, owner: current_user, date: event_date  
          @event.create_activity :submit_events, owner: current_user, date: @event.to 
        else
          @event.create_activity :submit_events, owner: current_user, date: event_date        
        end  
        
        flash[:notice] = 'Event was successfully created and emailed people that you have selected.'
        format.html { redirect_to(event_url(@event)) }
      else
        flash[:warning] = 'warning.'
        format.html { render :new }
      end
    end
  end
  
  def update
    @event = Event.find(params[:id])
    @activities = PublicActivity::Activity.all
    
    @activities = @activities.all(:conditions => ['trackable_id =? AND trackable_type =?',@event.id,'Event'])
    @activities.each{ |a| a.destroy }
    
    respond_to do |format|
      if @event.update_attributes(event_params)
        
        dt1 = @event.from.to_date
        dt2 = @event.to.to_date
        
        days_ctr = dt2 - dt1
        event_date = @event.from
        i = 1
        if days_ctr.to_i > 1
          days_ctr.to_i.times do
            @event.create_activity :submit_events, owner: current_user, date: event_date 
            event_date = event_date + 1.day
          end
          @event.create_activity :submit_events, owner: current_user, date: @event.to 
        elsif days_ctr.to_i == 1
          @event.create_activity :submit_events, owner: current_user, date: event_date  
          @event.create_activity :submit_events, owner: current_user, date: @event.to 
        else
          @event.create_activity :submit_events, owner: current_user, date: event_date        
        end
        
         ids = @event.event_people
         @people = Person.where(:id => ids.split(','))
        
         for person in @people
           KairosMailer.update_event(person,current_user,@event).deliver
         end
        
         flash[:notice] = 'Event was successfully updated.'
         format.html { redirect_to(event_url(@event)) }
      else
        format.html { render :edit }                
      end  
    end    
  end
  
  def destroy
    @event = Event.find(params[:id])
    
    @activities = PublicActivity::Activity.all
    
    @activities = @activities.all(:conditions => ['trackable_id =? AND trackable_type =?',@event.id,'Event'])
    @activities.each{ |a| a.destroy }
    @event.destroy
    
    flash[:notice] = "event request has been deleted"

    respond_to do |format|
      format.html { redirect_to(events_url) }
    end
  end            
  
  def submit_events
    @submitted_events = Event.where(:id => params[:events])
    @submitted_events.update_all(:is_submitted => true)  
    
    @people = Person.find(params[:people])
    people_ids = @people.map {|p| p.id}.join(",")  
        
    for person in @people
      KairosMailer.create_event(person,current_user,@submitted_events,@people).deliver
    end
      
    for event in @submitted_events
      event.event_people = event.event_people + "," + people_ids
      event.save
      #event.create_activity :submit_events, owner: current_user, date: event.date
    end  
    @events = Event.all

    respond_to do |format|
      flash[:notice] = "People was successfully notified."
      format.js {} 
    end
  end
  
  def add_people
    @event = Event.find(params[:id])
    
    @added_people = Person.find(params[:people])
    people_ids = @added_people.map {|p| p.id}.join(",")  
    
    @event.event_people = @event.event_people + "," + people_ids
    @event.save
    
    for person in @added_people
      KairosMailer.add_people(person,current_user,@event).deliver
    end
    
    ids = @event.event_people
    @added_people = Person.where(:id => ids.split(','))
    @people = Person.where.not(id: ids.split(','))
    
    respond_to do |format|
      flash[:notice] = "People was successfully added."
      format.js {} 
    end
  end
  
  def remove_person
    @event = Event.find(params[:id])
    ids = @event.event_people
    remove = params[:person]
    ids = ids.gsub(remove.to_s,'')    
    
    @event.event_people = ids
    @event.save
        
    @added_people = Person.where(:id => ids.split(','))
    @people = Person.where.not(id: ids.split(','))
    
    @person = Person.find(remove)
    KairosMailer.remove_person(@person,current_user,@event).deliver
    
    respond_to do |format|
      flash[:notice] = "Person was successfully removed."
      format.js {} 
    end
  end
  
  private
  
  def event_params 
    params.require(:event).permit(:from,:to,:date,:description, :title, :is_submitted, :event_people)
  end
end  

app/views/events/_details2.html.erb
<div class='details2'>
	<div class='end_form'> 
   <%= render :partial => 'submit_form' %>	
   </div>
</div>

app/views/events/_events.html.erb
<div style='padding:5px;overflow:auto;border-bottom: 1px solid #dddddd'>
  
  <div style='padding:5px;width: 30px;float:left'>
	<% check_box_tag("master",1,false,{ :id => "select_all", :onclick => "toggleItems(this,'events')" }) %>
  </div>
</div>


<% for event in @events %>
<div style='padding:5px;overflow:auto;border-bottom: 1px solid #dddddd'>
  
 
  <div style='padding:5px;width: 600px;float:left;margin-left:10px'>
    <div style='font-size:20px;font-weight:bold;color: #437927'>
      <%= event.title %><br/>
	  <div style='float:right;font-size:10px'>
        <%= link_to 'more info', event_path(event) %> |
        <%= link_to 'edit', edit_event_path(event) %>
	  </div>		
    </div>
	<div style='font-size:10px;margin-top:5px'>created by <%= creator_name(event.creator) %></div><br/>
	<%= event.from.strftime('%B %d, %Y') %> <b><em>to</em></b> <%= event.to.strftime('%B %d, %Y') %><br/>
	
	<div style='margin-top:10px'><%= event.description %></div>
  </div>	
</div>	
<% end %>

app/views/events/_form.html.erb
<script>
   $(document).ready(function() {
	$('#event_from').datepicker({
	  format: "yyyy-mm-dd",
	  autoclose: true		
	});
	$('#event_to').datepicker({
	  format: "yyyy-mm-dd",
	  autoclose: true		
	});
  });	
</script>
<div class="span8 body_layout">
   <div class='own_page_header'>		
     <h3>New Event</h3>
   </div>
 	
   <div style='padding:20px' id='calendar'>
	<%= form_for @event, :html => { :class => 'form-horizontal' } do |f| %>
	  <div class="control-group">
	    <%= f.label :from, :class => 'control-label' %>
	    <div class="controls">
	      <%= f.text_field :from, :class => 'text_field' %>
	    </div>
	  </div>
	
	  <div class="control-group">
	    <%= f.label :to, :class => 'control-label' %>
	    <div class="controls">
	      <%= f.text_field :to, :class => 'text_field' %>
	    </div>
	  </div>
	
	  <div class="control-group">
	    <%= f.label :title, :class => 'control-label' %>
	    <div class="controls">
	      <%= f.text_field :title, :class => 'text_field' %>
	    </div>
	  </div>

	  <div class="control-group">
	    <%= f.label :description, :class => 'control-label' %>
	    <div class="controls">
	      <%= f.text_area :description, :class => 'text_field' ,:size => '20x10' %>
	    </div>
	  </div>
	  <%= f.submit nil, :class => 'btn btn-primary' %>
   </div>
</div>
<% end %>

app/views/events/_people_js.html.erb
<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $('.icon-remove').popover(
	  {
	     trigger: 'hover',
	     html: true,
	     placement: 'right',
	     content: '<div style="background: blue;color:white;padding:5px"><b>Are you sure you want to remove this person from this event?</b></div> <br/> This will remove the person from this event.<br/><br/> Click <font style="color:red">x</font> to cancel.'
	  });    

	$(".icon-remove").click(function(){
	  	var id = $('#event_id').val();
		var person = $(this).attr('id');
		$.ajax({
		  type: "PUT",
		  dataType: "script",
		  url: "http://"+location.host+"/remove_person/",
		  data: {id: id, person: person},
	      beforeSend: function(data)
		  {
		    $('.spin_' + person).show();
		  },
		  success: function(response)
		  {
			$(this).hide(); 
		    $('.spin_'+ person).hide();
		  }
	    });
		return false;
    });
});
</script>

app/views/events/_show_js.html.erb
<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $('.icon-remove').popover(
	  {
	     trigger: 'hover',
	     html: true,
	     placement: 'right',
	     content: '<div style="background: blue;color:white;padding:5px"><b>Are you sure you want to remove this person from this event?</b></div> <br/> This will remove the person from this event.<br/><br/> Click <font style="color:red">x</font> to cancel.'
	  });    

	$(".icon-remove").click(function(){
	  	var id = $('#event_id').val();
		var person = $(this).attr('id');
		$.ajax({
		  type: "PUT",
		  dataType: "script",
		  url: "http://"+location.host+"/remove_person/",
		  data: {id: id, person: person},
	      beforeSend: function(data)
		  {
		    $('.spin_' + person).show();
		  },
		  success: function(response)
		  {
			$(this).hide(); 
		    $('.spin_'+ person).hide();
		  }
	    });
		return false;
    });

	$("#submit_events").click(function(){

	  var arr_people = new Array();
	
	  $('#test input[type="checkbox"]:checked').each(function() {
        arr_people.push($(this).val());
	  });
    		
	  if(arr_people.length === 0){
		$('#submit_modal').modal();
		$('#modal-message').html("Please select people to add!");
		$('#submit_link').hide();
		return false;
	  }
	  else{
		$('#submit_modal').modal();
		$('#modal-message').html("Are you sure you want to approve selected?");
		$('#submit_link').show();
		return false
	  } 
    });	
	
    $('#submit_link').click(function(){
	     var arr_people = new Array();
	     var id = $('#event_id').val();
	   
		 $('#test input[type="checkbox"]:checked').each(function() {
		   arr_people.push($(this).val());
		 });
		
	  	 $.ajax({
		      type: "PUT",
		      dataType: "script",
		      url: "http://"+location.host+"/add_people/",
		      data: {people: arr_people, id: id},
		      beforeSend: function(data)
		      {
			    $('#spin').show();
		      },
		      success: function(response)
		      {
			    $('#spin').hide();
				$('#submit_modal').modal('hide'); 				
		      }
		 });
		return false;
    });
  });
</script>

app/views/events/_submit_form.html.erb
<%= render partial: 'submit_form_js' %>

<div class='own_page_header'>	
  <h5>
	<h5>Select people to add in this event</h5>	
  </h5>
</div>
 
<div id="submit_modal" class="modal hide fade in" style="display: none; ">  
  <div class="modal-header">  
    <a class="close" data-dismiss="modal">×</a>  
    <font style='color:green'><h4>Submit Request!</h4></font>  
  </div>  
  <div class="modal-body">   
    <div id='modal-message'>Are you sure you want to notify selected people?</div> <div id='spin'>
	  processing <%= image_tag 'spin.gif' %>
	</div></p>                
  </div>  
  <div class="modal-footer">  
    <a href="#" class="btn btn-success" id='submit_link'>Send a notification</a>  
    <a href="#" class="btn" data-dismiss="modal">Cancel</a>  
  </div>  
</div>

<div style='padding-left:20px;padding-bottom:20px' id='test'>

	<% for person in @people do %>
	  <% if person.id != current_user.id  %>
	  <%= check_box_tag("people[]",person.id,false,{:class => person.id }) %>&nbsp;<span><%= person.first_name + " " + person.last_name %></span></br>
	  <% end %> 
	<% end %>
	
	<br/>
	
	<span class="label label-success" id= 's' style='display:none;margin-bottom:20px'>Successfully Submitted</span>
	
    <div class = 'btn btn-primary' id='submit_events' >
      Add People
    </div>
</div>

app/views/events/_submit_form_js.html.erb
<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {

	$("#submit_events").click(function(){

	  var arr_people = new Array();
	
	  $('#test input[type="checkbox"]:checked').each(function() {
        arr_people.push($(this).val());
	  });
    		
	  if(arr_people.length === 0){
		$('#submit_modal').modal();
		$('#modal-message').html("Please select people to add!");
		$('#submit_link').hide();
		return false;
	  }
	  else{
		$('#submit_modal').modal();
		$('#modal-message').html("Are you sure you want to approve selected?");
		$('#submit_link').show();
		return false
	  } 
    });	
	
    $('#submit_link').click(function(){
	     var arr_people = new Array();
	     var id = $('#event_id').val();
	   
		 $('#test input[type="checkbox"]:checked').each(function() {
		   arr_people.push($(this).val());
		 });
		
	  	 $.ajax({
		      type: "PUT",
		      dataType: "script",
		      url: "http://"+location.host+"/add_people/",
		      data: {people: arr_people, id: id},
		      beforeSend: function(data)
		      {
			    $('#spin').show();
		      },
		      success: function(response)
		      {
			    $('#spin').hide();
				$('#submit_modal').modal('hide'); 
				$('.modal-backdrop').hide(); 
								
		      }
		 });
		return false;
    });
  });
</script>

app/views/events/add_people.js.erb
$('#people_list').replaceWith("<%= escape_javascript(render("people")) %>");
$(".details2").replaceWith("<%= escape_javascript(render(:partial => "details2")) %>");
$(".end_form").replaceWith("<%= escape_javascript(render(:partial => "details2")) %>");

<%= flash_notice(flash.first[1], flash.first[0]) unless flash.blank? %>

app/views/events/edit.html.erb
<%= render partial: 'form' %> 	

app/views/events/index.html.erb
<div class="span9 body_layout">
 <div class='own_page_header'>		
   <h3>Events</h3>

	<div class='pull-right' style='margin-top:-40px'>
	  <%= link_to 'Create Event',
	            new_event_path, :class => 'btn' %>
	</div>
 </div>
 
 <div style='padding:10px' id='events_list'>
   <%= render partial: 'events' %>
 </div>
 <br/><br/>
</div>

app/views/events/new.html.erb
<%= render partial: 'form' %> 	

app/views/events/remove_person.js.erb
$('#people_list').html("<%= escape_javascript(render("people")) %>");
<%= flash_notice(flash.first[1], flash.first[0]) unless flash.blank? %>

app/views/events/show.html.erb
<div class="span8 body_layout">
   <div class='own_page_header'>		
     <h3><%= @event.title %></h3>
	 created by <%= creator_name(@event.creator) %><br/>
	 <%= link_to 'edit this event', edit_event_path(@event) %>
   </div>

   <div style='padding:20px'>
	 <b>From:</b> <%= @event.from.strftime('%B %d, %Y') %> <br/>
	 <b>To:</b> <%= @event.to.strftime('%B %d, %Y') %> 
	 <br/><br/>
		
     <%= @event.description %> 
     <%= hidden_field_tag :event_id, @event.id %>
	 <br/><br/><br/>
	  
	 <b>People who will join this event</b><br/><br/> 
	
     <div id='people_list'>
	   <%= render partial: 'people' %>
	 </div> 
   </div>	

<br/>	
</div>

	<div class="span3 side_layout">
	  <div class="sidebar-nav">
	    <div id='forms'>
	      <div class='details2'>
	        <%= render :partial => 'details2' %>  	
	      </div>	
	</div>
	</div>
	</div>	

<div class="span3">
     <div id='red_link' style='padding:10px'>
        <%= link_to "Delete this event",event_path(@event),
                      :method => :delete,  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %>
     </div>
<br/>
</div>	
	

app/views/events/submit_events.js.erb
$('#events_list').html("<%= escape_javascript(render("events")) %>");
<%= flash_notice(flash.first[1], flash.first[0]) unless flash.blank? %>