config/routes.rb
Kairos::Application.routes.draw do

  
  
  match "/" => "application#index", :as => :application, via: [:get,:post]
  
  resources :activities
  match 'calendar', to: 'activities#calendar', as: :calendar, via: [:get, :post]
  
  resources :leaves
  match "submit_leaves" => "leaves#submit_leaves", :via => [:put]
  match "cancel_leave" => 'leaves#cancel_leave', :via => [:put]
  
  resources :person_tasks do
    collection do
      put 'submit_tasks'
    end
  end
    
  resources :people
  resources :rights
  resources :events
  
  match "submit_events" => "events#submit_events", :via => [:put]
  match "remove_person" => 'events#remove_person', :via => [:put]
  match "add_people" => 'events#add_people', :via => [:put]
  
  match 'login', to: 'login#login', as: :login ,via: [:get, :post]
  match 'logout', to: 'login#logout', as: :logout, via: [:get, :post]
  match 'dashboard', to: 'person_tasks#dashboard', as: :dashboard, via: [:get, :post]
  match "has_seen" => 'activities#has_seen', :via => [:put]
  
  match 'set_date', to: 'login#set_date', as: :set_date , via: [:get, :post]
  match "submit_tasks" => "person_tasks#submit_tasks", :via => [:put]
  match "get_tasks_assignments" => 'tasks#get_tasks_assignments', :via => [:get]
  match "create_role_task" => 'tasks#create_role_task', :via => [:post]
  match "deactivate_role_task" => 'tasks#deactivate_role_task', :via => [:put]
  match "activate_role_task" => 'tasks#activate_role_task', :via => [:put]
  
  resources :tasks
  
  match "tasks_report" => 'reports#tasks_report', :via => [:get,:post]
  match "utilization_rates" => 'reports#utilization_rates', :via => [:get,:post]
  match "search_tasks" => 'reports#search_tasks', :via => [:get,:post]
  match "search_rates" => 'reports#search_rates', :via => [:get,:post]
  
  match "add_tasks_to_role" => "manage#add_tasks_to_role", :via => [:get, :post]
  match "get_specific_tasks_assignments" => 'specific_tasks#get_specific_tasks_assignments', :via => [:get]
  match "get_role_task" => 'specific_tasks#get_role_task', :via => [:get]
  match "create_specific_role_task" => 'specific_tasks#create_specific_role_task', :via => [:post]
  
  resources :specific_tasks
  match "deactivate_role_specific_task" => 'specific_tasks#deactivate_role_specific_task', :via => [:put]
  match "activate_role_specific_task" => 'specific_tasks#activate_role_specific_task', :via => [:put]
  
  match "tasks_approval" => 'approvals#tasks_approval', :via => [:get,:post]
  match "leaves_approval" => 'approvals#leaves_approval', :via => [:get,:post]
  
  match "approve_tasks" => 'approvals#approve_tasks', :via => [:put]
  match "disapprove_tasks" => 'approvals#disapprove_tasks', :via => [:put]
  
  match "approve_leaves" => 'approvals#approve_leaves', :via => [:put]
  match "disapprove_leaves" => 'approvals#disapprove_leaves', :via => [:put]
  
  match "end_task" => 'person_tasks#end_task', :via => [:put]
  match "generate_spreadsheets" => "reports#generate_spreadsheets", :as => :generate_spreadsheets, :via => [:get, :post]
  
end

app/models/person_task.rb
class PersonTask < ActiveRecord::Base  
  include PublicActivity::Common
  belongs_to :person
  belongs_to :task
  belongs_to :specific_task
  
  #attr_accessible :activity_id, :specific_activity_id
  
  #boolean methods
  def is_submitted?
    is_submitted == true && is_disapproved == false && is_approved == false
  end
  
  def is_approved?
    is_submitted == true && is_approved == true && is_disapproved == false
  end
  
  def is_disapproved?
    is_submitted == true && is_disapproved == true && is_approved == false
  end
  
  
  #class methods
  def self.find_tasks_to_be_approved(person,*associations,user)
    associations = []
    where = Where.new
    
    if user.is_admin?
      if !person.blank?
        
        where.and('organizations.name LIKE ?', "%#{user.organization.name}%") 
        where.and('person_tasks.person_id = ?',person) 
      else
        where.and('organizations.name LIKE ?', "%#{user.organization.name}%")
      end
    else
      if !person.blank?  
        where.and('departments.name LIKE ?', "%#{user.department.name}%") 
        where.and('organizations.name LIKE ?', "%#{user.organization.name}%")
        where.and('person_tasks.person_id = ?',person) 
      else
        where.and('departments.name LIKE ?', "%#{user.department.name}%") 
        where.and('organizations.name LIKE ?', "%#{user.organization.name}%")     
      end     
    end
   
    where.and('person_tasks.is_submitted = ? AND (person_tasks.is_approved = ? OR person_tasks.is_disapproved = ?)', "1", "0", "1")
    
    associations << [:task,:specific_task,{:person => [:department, :organization] }]
    person_tasks = PersonTask.scoped({})
    
    person_tasks = person_tasks.all(:include => associations.uniq,:conditions => where.to_s, :order =>'person_tasks.start DESC, person_tasks.person_id')  
  end
  
  def self.approve_tasks(ids,current_user)
    person_tasks = where(:id => ids)    
    for person_task in person_tasks
      person_task.approve_task(person_task,current_user)  
    end  
  end  
  
  def approve_task(person_task,current_user)
    if !person_task.task_id.nil? && !person_task.specific_task_id.nil?
      person_task.is_approved = true
      person_task.is_disapproved = false
      person_task.approved_by = current_user.id
      person_task.save!  
    end
  end  
  
  def self.disapprove_tasks(ids,current_user)
    person_tasks = where(:id => ids)    
    for person_task in person_tasks
      person_task.disapprove_task(person_task,current_user)  
    end  
  end  
  
  def disapprove_task(person_task,current_user)
    if !person_task.task_id.nil? && !person_task.specific_task_id.nil?
      person_task.is_approved = false
      person_task.is_disapproved = true
      person_task.approved_by = current_user.id
      person_task.save!  
    end
  end
  
  def self.calculate_total_hours(ids,show=nil)
   # ids = activities.map {|c| c.id}
    hours = 0
    minutes = 0
    seconds = 0
    activities = find(ids)
    activities.each do |f|
      
      should_change_seconds = "false"
      should_change_minutes = "false" 
      
      seconds += f.total_time.strftime('%S').to_i if !f.total_time.nil?
      if seconds >= 60
        should_change_seconds = "true"
      end
      minutes += f.total_time.strftime('%M').to_i if !f.total_time.nil?
      if minutes >= 60
        should_change_minutes = "true" 
      end 
      if should_change_seconds == "true" 
        minutes += 1
        seconds = seconds - 60
      end
      if should_change_minutes == "true" 
        hours += 1
        minutes = minutes - 60
      end
      hours += f.total_time.strftime('%H').to_i if !f.total_time.nil?     
    end
    if show =="hours"
      hours
    elsif show =="minutes"
      minutes
    else
      seconds  
    end
  end
  
  def self.search(search,time,current_user)
    if !search.blank?
      start = search + " " + "00:00:00"
      endt = search + " " + "23:59:59"
      where(["person_tasks.start >=? AND person_tasks.start <=? AND person_id =?",start,endt,current_user.id]).order("start DESC").includes(:task, :specific_task) 
    else
      where(["person_tasks.start >=? AND person_tasks.start <=? AND person_id =?",time.beginning_of_day,time.end_of_day,current_user.id]).order("start DESC").includes(:task, :specific_task)  
    end    
  end  
  
  def self.fetch_productive_hours(search,time,current_user)
    personal_id = Task.find_by_name("Personal Time").id
    break_id = Task.find_by_name("Break").id
    avail_id = Task.find_by_name("Avail Time").id
    
    @tasks = search(search,time,current_user)
    
    @tasks.where(["person_tasks.task_id !=? AND person_tasks.task_id !=? AND person_tasks.task_id !=?",break_id,personal_id,avail_id])
  end
  
  def self.fetch_break_hours(search,time,current_user)
    @break_id = Task.find_by_name("Break").id
    
    @tasks = search(search,time,current_user)
    @tasks.where(["person_tasks.task_id =?",@break_id])
  end
  
  def self.fetch_unfinished_tasks_today(search,time,current_user)
    @tasks = search(search,time,current_user)
    @tasks = @tasks.where(["task_id IS NULL"]).order("start DESC").includes(:task, :specific_task)
  end
  
end  

app/controllers/person_tasks_controller.rb
class PersonTasksController < ApplicationController
  require 'time_diff'
  include ActionView::Helpers::NumberHelper
  include PublicActivity::StoreController
  
  before_filter :authorize
      
  def index
    session[:search] = nil
    session[:time] = nil
    session[:user] = nil
    
    @tasks = PersonTask.search(params[:search],set_user_time_zone,current_user).includes(:task, :specific_task)
    @productive = PersonTask.fetch_productive_hours(params[:search],set_user_time_zone,current_user).includes(:task, :specific_task)
    
    @break = PersonTask.fetch_break_hours(params[:search],set_user_time_zone,current_user).includes(:task, :specific_task)
    
    @unfinished = PersonTask.fetch_unfinished_tasks_today(params[:search],set_user_time_zone,current_user).includes(:task, :specific_task)
    session[:search] = params[:search]
  end    
  
  def dashboard
    @activities = PublicActivity::Activity.order("created_at desc").where(recipient_id: current_user.id)
    @activities_has_seen = PublicActivity::Activity.order("created_at desc").where(recipient_id: current_user.id, has_seen: true)   
       
  end  
  
  def edit
    @task = PersonTask.find(params[:id])
  end
  
  def end_task
    
    unless params[:person_task][:task_id].blank?
    @message = 'Successfully ended!'
    @task = PersonTask.find(params[:person_task][:id])
    if @task.update_attributes(user_params)
      @task.end = set_user_time_zone
      @task.save
    
      difference = Time.diff(Time.parse(@task.start.strftime('%Y-%m-%d  %H:%M:%S')), Time.parse(@task.end.strftime('%Y-%m-%d %H:%M:%S')), '%h:%m:%s')
      total_time = difference[:hour].to_s + ":" + difference[:minute].to_s + ":" + difference[:second].to_s

      @task.total_time = total_time
      @task.save
    
      @tasks = PersonTask.search(session[:search],set_user_time_zone,current_user).includes(:task, :specific_task)
      @productive = PersonTask.fetch_productive_hours(session[:search],set_user_time_zone,current_user).includes(:task, :specific_task)

      @break = PersonTask.fetch_break_hours(session[:search],set_user_time_zone,current_user).includes(:task, :specific_task)
      @unfinished = PersonTask.fetch_unfinished_tasks_today(session[:search],set_user_time_zone,current_user).includes(:task, :specific_task)
    
        if params[:end_shift] == 'yes'
          new_activity = PersonTask.create!(:person_id => current_user.id,:start => @task.end,:created_at => set_user_time_zone) 
        end
      end
    else
      @message = 'Select a task first!'
      flash[:warning] = @message 
    end
      
    respond_to do |format| 
      format.js
    end    

  end  
  
  def update
    @task = PersonTask.find(params[:id])
      if @task.update_attributes(user_params)  
       if !@task.end.nil?
         difference = Time.diff(Time.parse(@task.start.strftime('%Y-%m-%d  %H:%M:%S')), Time.parse(@task.end.strftime('%Y-%m-%d %H:%M:%S')), '%h:%m:%s')
         total_time = difference[:hour].to_s + ":" + difference[:minute].to_s + ":" + difference[:second].to_s

         @task.total_time = total_time
         @task.save
         
         @tasks = PersonTask.search(session[:search],set_user_time_zone,current_user).includes(:task, :specific_task)
         @productive = PersonTask.fetch_productive_hours(session[:search],set_user_time_zone,current_user).includes(:task, :specific_task)

         @break = PersonTask.fetch_break_hours(session[:search],set_user_time_zone,current_user).includes(:task, :specific_task)
         @unfinished = PersonTask.fetch_unfinished_tasks_today(session[:search],set_user_time_zone,current_user).includes(:task, :specific_task)
       end
       respond_to do |format|   
         format.html {redirect_to search_tasks_url}
         flash[:notice] = "Your task was successfully updated!"  
       end  
    end     
  end
  
  def destroy
    @person_task = PersonTask.find(params[:id])
    @person_task.destroy

    respond_to do |format|
      flash[:notice] = "Activity was successfully deleted!"
      format.html { redirect_to :back }
    end  
  end  
  
  def submit_tasks
    @tasks = PersonTask.search(session[:search],set_user_time_zone,current_user).includes(:task, :specific_task)
    @tasks.update_all(:is_submitted => true)  
    
    @people = Person.find(params[:people])
    
    if session[:search].blank?
      shift_date = set_user_time_zone.strftime('%Y-%m-%d')
    else
      shift_date = session[:search]
    end
   
    @total_hour = UtilizationRate.where(["shift_date =? AND person_id =?",shift_date,current_user.id])
    @productive_hours = PersonTask.fetch_productive_hours(shift_date,set_user_time_zone,current_user).includes(:task, :specific_task)
    
    @hours = PersonTask.calculate_total_hours(@productive_hours.map {|a| a.id},"hours")
    @minutes = PersonTask.calculate_total_hours(@productive_hours.map {|a| a.id},"minutes")
    
    @th = number_with_precision(UtilizationRate.save_utilization_rate(@hours,@minutes),:precision => 2)
    
    if @total_hour.count == 0    
      UtilizationRate.create!(:person_id => current_user.id,:total_utilization_rate => @th, :shift_date => shift_date)
    else
      @total_hour.last.total_utilization_rate = @th.to_f
      @total_hour.last.save
    end
      
    for person in @people
      KairosMailer.send_approvals(person,current_user,shift_date).deliver
      #@public_activity = PublicActivity.create(owner_type: "Person", trackable_type: 'PersonTask', owner_id: current_user.id, key: 'person_task.submit_tasks')
      @tasks.first.create_activity :submit_tasks, owner: current_user, recipient: person, date: shift_date
    end
    
    respond_to do |format|
      flash[:notice] = "Today Tasks was successfully submitted!" 
      format.js   { } 
    end
  end  
  
  private

  def user_params
    params.require(:person_task).permit(:person_id, :task_id, :specific_task_id, :person_in_charge, :note, :start,:end)
  end         
end  
  

app/views/person_tasks/_act.html.erb
<tr id='hey'><tr>
<tr id ='task_<%= task.id %>'>

    
     <td><%= task.task.name if !task.task_id.nil?  %></td>
     <td><%= task.task.name if !task.task_id.nil? %></td>
     <td><%= task.created_at.strftime('%l:%M:%S %p').downcase %></td>
     <td><%= task.updated_at.strftime('%l:%M:%S %p').downcase if !task.task_id == nil %></td>
     <td><%= task.total_time.strftime('%l:%M:%S').downcase if !task.total_time.nil? %> </td>
 	 <td>
		
		 <%= link_to t('.edit', :default => t("helpers.links.edit")),
	                 edit_person_task_path(task), :class => 'btn btn-mini' if !task.task_id.nil? && current_user.role.name == '1st Level User' %>
       <% link_to t('.destroy', :default => t("helpers.links.destroy")),
                 person_task_path(task),
                 :method => :delete,
                 :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                 :class => 'btn btn-mini btn-danger' %>
 	</td>
   </tr>

app/views/person_tasks/_dashboard_activities.html.erb
	<script>
	  $(document).ready(function(){
	    $('#eye div').click(function(){
		  var id = $(this).attr('id');
	      	 $.ajax({
			      type: "PUT",
			      dataType: "script",
			      url: "has_seen",
			      data: {id: id},
			      beforeSend: function(data)
			      {
				   $(this).children("#spin").show(); 
			       },
			       success: function(response)
			       {
					$(this).children("#spin").show(); 
			       }
			       });
			return false;
	    });	
	  });
	</script>
	
	<% for activity in @activities do %>
		<% if activity.has_seen == false %><div class = 'dash_noti blue_bg' id = "noti_<%= activity.id %>" ><% end %>
		<% if activity.has_seen == true %><div class = 'dash_noti'><% end %>
		  <div class='noti_pic'>
		    <%= image_tag avatar_url_normal(activity.owner), :class => 'img-rounded' %>  	
		  </div>
		  <div class='noti_info'> 			
		    
		    <font style='color:#bbb'><%= time_ago_in_words(activity.created_at) %></font><br/>
            <font style='color:#4183c4'><b><%= activity.owner.name if activity.owner %></font></b>
            
			<% if activity.key == 'person_task.submit_tasks' %>
			  submitted his/her tasks for <b><%= activity.date %></b> to  <font style='color:#4183c4'><b><%= activity.recipient.name if activity.recipient %></b></font>
			<% elsif activity.key == 'leave.submit_leaves' %>
			  submitted his/her leave request for <b><%= activity.date.strftime('%b. %e, %Y') %></b><br/>
			  you can now approve it.
			
			<% elsif activity.key == 'leave.cancel_leave' %>
			  has canceled his leave request for <b><%= activity.date.strftime('%b. %e, %Y') %></b><br/>
			
			<% elsif activity.key == 'leave.approve_leaves' %>
			  approved your leave request for <b><%= activity.date.strftime('%b. %e, %Y') %></b><br/>
			
			<% elsif activity.key == 'leave.disapprove_leaves' %>
			  disapproved your leave request for <b><%= activity.date.strftime('%b. %e, %Y') %></b><br/>
			<% end %>
			
		  </div>
		  <div id ='spin'><%= image_tag 'spin.gif' %></div>	
		  <div class='pull-right'>
			<br/>
		    <% if activity.has_seen == false %><div class="btn tbn-success" id = "eye" ><div class='icon-eye-open' id = "<%= activity.id %>"></div></div><% end %>
		  </div>	
		</div>
      <% end %>

app/views/person_tasks/_details.html.erb
<div class='details'>  
  <div id='progress'> 
    <%= render :partial => 'progress_bar', :locals => { :rate => @rate } %>
  </div>
  <div id='time_summary'>
    <%= render :partial => 'time_summary' %>
  </div>
</div>

app/views/person_tasks/_details2.html.erb
<div class='details2'>
  <div class='end_form'> 
	<% if @unfinished.count == 0 %>
	   <%= render :partial => 'submit_form' %>	
    <% else %>
       <%= render :partial => 'end_task_form' %> 
    <% end %>
  </div>	
</div>	

app/views/person_tasks/_end_task_form_js.html.erb
<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
   	var specific_activities = $("#person_task_specific_task_id").html();
    $("#person_task_specific_task_id").prop("disabled", true);


	  $('#person_task_task_id').change(function(){
	   var task = $('#person_task_task_id :selected').text();
	   var escaped_parent = task.replace(/([ #;&,.+*~\':"!^$[\]()=>|\/@])/g, '\\$1');
	   var options = $(specific_activities).filter("optgroup[label='" + escaped_parent + "']").html();
	    if (options){
	      $("#person_task_specific_task_id").html(options);
	      $("#person_task_specific_task_id").prop("disabled", false);
	      return jQuery('person_task_specific_task_id').parent().show();
	    }
	    else{
	      $("#person_task_specific_task_id").empty();
		  $("#person_task_specific_task_id").prop("disabled", true);
	    } 	
	    });
	
	
	$('#submit_task').popover(
	  {
	     trigger: 'hover',
	     html: true,
	     placement: 'left',
	     content: 'This button will end your current task and automatically create another one if you choose to continue'
	  });
	    
	$("#submit_task").click(function(){
	  dataString = $(".submit_task_form").serialize();
	  $.ajax({
	    type: "PUT",
	    dataType: "script",
	    url: "end_task",
	    data: dataString,
	    beforeSend: function(data)
	    {
	      $('#spin').show();
	      $("#submit_task").hide();	   
	    },
	    success: function(response)
		{
	      $('#spin').hide();
		  $("#submit_task").show();	   	
		}
	   });
       return false;
	 });	  	  
  });	
</script>

app/views/person_tasks/_progress_bar.html.erb
<%= render partial: 'progress_bar_js' %>
<% @hours = PersonTask.calculate_total_hours(@productive.map {|a| a.id},"hours") %>
<% @minutes = PersonTask.calculate_total_hours(@productive.map {|a| a.id},"minutes") %>  
<% @rate = compute_utilization_rate(@hours,@minutes).to_f %>
<%= hidden_field_tag :rate, @rate, :id => 'rate' %>
<div id="progresBarContainer" class="progress">
  <% if @rate < 20 %>
    <div id="progresBarFill" class="bar bar-danger" ></div>
  <% elsif @rate > 15 && @rate < 100 %>
    <div id="progresBarFill" class="bar bar-warning" ></div>
  <% else %>
    <div id="progresBarFill" class="bar bar-success" ></div>
  <% end %>
</div>

app/views/person_tasks/_submit_form.html.erb
<%= render partial: 'submit_form_js' %>
<div class='own_page_header'>	
  <h5>
	<h5>Select people to notify</h5>	
	<div id='spin'>
	  <%= image_tag 'spin.gif' %>
	</div>
  </h5>
</div>
 
<div style='padding-left:20px;padding-bottom:20px' id='test'>


	<% for person in people_that_can_approve do %>
	
	  <%= check_box_tag("people[]",person.id,false,{}) %>&nbsp;<span><%= person.first_name + " " + person.last_name %></span></br>
	
	<% end %>
	
	<br/>
	
	<span class="label label-success" id= 's' style='display:none;margin-bottom:20px'>Successfully Submitted</span>
	
    <div class = 'btn btn-primary' id='submit_tasks' >
      Submit Tasks Today
    </div>
</div>

app/views/person_tasks/_task.html.erb
<tr id ='task_<%= task.id %>'>

    
     <td><%= task.task.name if !task.task_id.nil?  %></td>
     <td><%= task.specific_task.name if !task.specific_task_id.nil? %></td>
     <td><%= task.start.strftime('%l:%M:%S %p').downcase %></td>
     <td><%= task.end.strftime('%l:%M:%S %p').downcase if !task.task_id.nil?  %></td>
     <td><%= task.total_time.strftime('%H:%M:%S').downcase if !task.total_time.nil? %></td> 
     <td>
       <%= link_to t('.edit', :default => t("helpers.links.edit")),
                 edit_person_task_path(task), :class => 'btn btn-mini' if !task.task_id.nil? && current_user.role.name == '1st Level User' %>
       <% link_to t('.destroy', :default => t("helpers.links.destroy")),
                 person_task_path(task),
                 :method => :delete,
                 :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                 :class => 'btn btn-mini btn-danger' %>
 </td>
   </tr>

app/views/person_tasks/_tasks.html.erb
<table class="table table-striped">
   <thead>
     <tr>
       <th>Activity</th>
       <th>Specific Activity</th>     
       <th><%= "Start Time" %></th>
       <th><%= "End Time" %></th>
       <th><%= "Total Time" %></th>
   	   <th></th>	

     </tr>
   </thead>
   <tbody>
	 <tr id='hey' style='display:none'><tr>	
     <%= render partial: 'task', :collection => @tasks %>
   </tbody>
 </table>

app/views/person_tasks/end_task.js.erb
<% if @message == 'Successfully ended!' %>

  $("#task_<%= @task.id %>").replaceWith("<%= escape_javascript(render(:partial => "task", :locals => {:task => @task})) %>");
  $("#task_<%= @task.id %>").addClass('<%= cycle('odd','even') %>');
  <% if params[:end_shift] == 'yes' %>
    $("#hey").replaceWith("<%= escape_javascript(render(:partial => "act", :locals => {:task => @tasks.first})) %>");
  <% end %>
  $(".details").replaceWith("<%= escape_javascript(render(:partial => "details")) %>");
  $("#time_summary").replaceWith("<%= escape_javascript(render(:partial => "time_summary")) %>");
  $("#progress").replaceWith("<%= escape_javascript(render(:partial => "progress_bar")) %>");
  $(".details2").replaceWith("<%= escape_javascript(render(:partial => "details2")) %>");
  $(".end_form").replaceWith("<%= escape_javascript(render(:partial => "details2")) %>");

<% end %>

<%= flash_notice(flash.first[1], flash.first[0]) unless flash.blank? %>

app/views/person_tasks/index.html.erb
<script>
   $(document).ready(function() {
	$('.input-group.date').datepicker({
	  format: "yyyy-mm-dd",
	  autoclose: true		
	});
	
    $("#tasks_search input").change(function(){
		dataString = $("#tasks_search").serialize();
		  $.ajax({
		    type: "GET",
			dataType: "script",
			url: "/person_tasks",
			data: dataString,
			  beforeSend: function(data)
			  {
			    $('#spin').show();	   
			  },
			  success: function(response)
			  {
			    $('#spin').hide();	
			  }
		   });
		   return false;
    });	

  });
</script>

<%- model_class = PersonTask -%>

<div class="span9 body_layout">
  <div class='own_page_header'>	
   	 <h3>
       <%= 'Tasks Management' %><%= form_tag person_tasks_path, :method => 'get', :id => 'tasks_search', :class => "form-search pull-right" do %>
        <div class="input-group date input-append">
	       <div id='spin' style='margin-left:10px'><%= image_tag 'spin.gif' %></div>
	       <%= text_field_tag :search, '',:class => 'form-control' , :placeholder => 'enter shift date' %><span class="add-on" style='margin-top:2px'><i class="icon-th"></i></span>
	    </div>
	   <% end %>
    </h3>	
  </div>	
  <div style='padding:20px'>
    <div class="page-header" style='margin-top:-10px'>	
  
      <p>Goal is to reach hundred percent</p>
      <div id='summary'>
        <div class='details'>
	      <%= render :partial => 'details' %> 
        </div>
      </div>
    </div>
  
  <div id='tasks'>
    <%= render :partial => 'tasks', :locals => { :tasks => @tasks } %>
  </div>

  <% link_to t('.new', :default => t("helpers.links.new")),
            new_person_task_path,
            :class => 'btn btn-primary' %>
  </div>
</div>

<div class="span3 side_layout">
  <div class="sidebar-nav">
    <div id='forms'>
      <div class='details2'>
        <%= render :partial => 'details2' %>  	
      </div>
    </div>
  </div>
</div>

app/views/person_tasks/new.html.erb
<%- model_class = PersonTime -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/person_tasks/submit_tasks.js.erb
<%= flash_notice(flash.first[1], flash.first[0]) unless flash.blank? %>

app/views/person_tasks/update.js.erb
$("#task_<%= @task.id %>").replaceWith("<%= escape_javascript(render(:partial => "task", :locals => {:task => @task})) %>");
$("#task_<%= @task.id %>").addClass('<%= cycle('odd','even') %>');
<% if params[:end_shift] == 'yes' %>
  $("#hey").replaceWith("<%= escape_javascript(render(:partial => "act", :locals => {:task => @tasks.first})) %>");
<% end %>
$(".details").replaceWith("<%= escape_javascript(render(:partial => "details")) %>");
$("#time_summary").replaceWith("<%= escape_javascript(render(:partial => "time_summary")) %>");
$("#progress").replaceWith("<%= escape_javascript(render(:partial => "progress_bar")) %>");
$(".details2").replaceWith("<%= escape_javascript(render(:partial => "details2")) %>");
$(".end_form").replaceWith("<%= escape_javascript(render(:partial => "details2")) %>");

<%= flash_notice(flash.first[1], flash.first[0]) unless flash.blank? %>