config/routes.rb
Kairos::Application.routes.draw do

  
  
  match "/" => "application#index", :as => :application, via: [:get,:post]
  
  resources :activities
  match 'calendar', to: 'activities#calendar', as: :calendar, via: [:get, :post]
  
  resources :leaves
  match "submit_leaves" => "leaves#submit_leaves", :via => [:put]
  match "cancel_leave" => 'leaves#cancel_leave', :via => [:put]
  
  resources :person_tasks do
    collection do
      put 'submit_tasks'
    end
  end
    
  resources :people
  resources :rights
  resources :events
  
  match "submit_events" => "events#submit_events", :via => [:put]
  match "remove_person" => 'events#remove_person', :via => [:put]
  match "add_people" => 'events#add_people', :via => [:put]
  
  match 'login', to: 'login#login', as: :login ,via: [:get, :post]
  match 'logout', to: 'login#logout', as: :logout, via: [:get, :post]
  match 'dashboard', to: 'person_tasks#dashboard', as: :dashboard, via: [:get, :post]
  match "has_seen" => 'activities#has_seen', :via => [:put]
  
  match 'set_date', to: 'login#set_date', as: :set_date , via: [:get, :post]
  match "submit_tasks" => "person_tasks#submit_tasks", :via => [:put]
  match "get_tasks_assignments" => 'tasks#get_tasks_assignments', :via => [:get]
  match "create_role_task" => 'tasks#create_role_task', :via => [:post]
  match "deactivate_role_task" => 'tasks#deactivate_role_task', :via => [:put]
  match "activate_role_task" => 'tasks#activate_role_task', :via => [:put]
  
  resources :tasks
  
  match "tasks_report" => 'reports#tasks_report', :via => [:get,:post]
  match "utilization_rates" => 'reports#utilization_rates', :via => [:get,:post]
  match "search_tasks" => 'reports#search_tasks', :via => [:get,:post]
  match "search_rates" => 'reports#search_rates', :via => [:get,:post]
  
  match "add_tasks_to_role" => "manage#add_tasks_to_role", :via => [:get, :post]
  match "get_specific_tasks_assignments" => 'specific_tasks#get_specific_tasks_assignments', :via => [:get]
  match "get_role_task" => 'specific_tasks#get_role_task', :via => [:get]
  match "create_specific_role_task" => 'specific_tasks#create_specific_role_task', :via => [:post]
  
  resources :specific_tasks
  match "deactivate_role_specific_task" => 'specific_tasks#deactivate_role_specific_task', :via => [:put]
  match "activate_role_specific_task" => 'specific_tasks#activate_role_specific_task', :via => [:put]
  
  match "tasks_approval" => 'approvals#tasks_approval', :via => [:get,:post]
  match "leaves_approval" => 'approvals#leaves_approval', :via => [:get,:post]
  
  match "approve_tasks" => 'approvals#approve_tasks', :via => [:put]
  match "disapprove_tasks" => 'approvals#disapprove_tasks', :via => [:put]
  
  match "approve_leaves" => 'approvals#approve_leaves', :via => [:put]
  match "disapprove_leaves" => 'approvals#disapprove_leaves', :via => [:put]
  
  match "end_task" => 'person_tasks#end_task', :via => [:put]
  match "generate_spreadsheets" => "reports#generate_spreadsheets", :as => :generate_spreadsheets, :via => [:get, :post]
  
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
require 'will_paginate/array' 

  before_filter :authorize

  # GET /report
   def tasks_report
     @search = Search.new
     session[:person_task_search_cache] = nil
     session[:person_task_search_results] = nil
     session[:form_type] = 'basic_form'
     respond_to do |format|
       format.html { render :layout => 'application' } # index.html.erb
     end
   end
   
   def search_tasks
       @search = fetch_search(:person_task)
       session[:form_type] = params[:form_type]
       if @search.is_cached?
         # Search from the search cache
         @person_tasks = session[:person_task_search_results].nil? ?
           @search.find_tasks_new([:task,:specific_task,{:person => [:department, :organization] }]) :
           PersonTask.find(session[:person_task_search_results],
             :include => [:task,:specific_task, {:person => [:department, :organization] }],
             :order => 'person_tasks.start DESC,person_tasks.person_id')
         @total_count = @person_tasks.length    
         #@person_tasks = @person_tasks.collect
         @person_tasks = @person_tasks.paginate(:page => params[:page],:per_page => 100)   

       elsif @search.is_active?
         # Search from scratch
         @person_tasks = @search.find_tasks_new([:task,:specific_task,{:person => [:department, :organization] }])
         if @person_tasks.length >=1 && @person_tasks.length <= 1000
           session[:person_task_search_cache] = params[:search]
           #ids = @person_tasks.collect.map {|p| p.id}
           #session[:person_task_search_results] = ids
         else
           session[:person_task_search_cache] = nil
           session[:person_task_search_results] = nil
         end
         @total_count = @person_tasks.length 
        #person_tasks = @person_tasks.collect

        @person_tasks = @person_tasks.paginate(:page => params[:page],:per_page => 100)    
       else
         # Nothing to search
         flash[:warning] = "You must enter something to search for" if request.post?
       end

       respond_to do |format|
         format.html {
             render :layout => 'application'
         }
       end   
   end
   
   def generate_spreadsheets
      spreadsheets = {}
       @search = fetch_search(:person_task)
        tasks = session[:person_task_search_results].nil? ?
           @search.find_tasks_new([:task,:specific_task,{:person => [:department, :organization] }]) :
           PersonTask.find(session[:person_task_search_results],
             :include => [:task,:specific_task, {:person => [:department, :organization] }],
             :order => 'person_tasks.start DESC,person_tasks.person_id')
        template = "reports/tasks_report.xls.eku"  
        @tasks_or_rates = tasks
        @report_type = "tasks_report"
        spreadsheets["tasks_report.xls"] = 
        render_to_string(:template => template)
                
        public_filename = Archiver.bundle(spreadsheets,@report_type)

        send_file(File.join("public",public_filename), :disposition => 'attachment') 
   end        
   
   def utilization_rates
      @search = Search.new
      session[:search_rate_search_cache] = nil
      session[:search_rate_search_results] = nil

      respond_to do |format|
        format.html { render :layout => 'application' } # index.html.erb
      end
   end
   
   def search_rates
     @search = fetch_search(:utilization_rate)
      if @search.is_cached?
        # Search from the search cache
        @utilization_rates = session[:utilization_rate_search_results].nil? ?
         @search.find_rates([{:person => [:department, :organization]}]) :
          UtilizationRate.find(session[:utilization_rate_search_results],
            :include => [{:person => [:department, :organization]}],
            :order => 'utilization_rates.shift_date DESC,utilization_rates.person_id')
        @total_count = @person_tasks.length    
        #@person_tasks = @person_tasks.collect
        @utilization_rates = @utilization_rates.paginate(:page => params[:page],:per_page => 100)   

      elsif @search.is_active?
        # Search from scratch
        @utilization_rates = @search.find_rates([{:person => [:department, :organization]}])
        if @utilization_rates.length >=1 && @utilization_rates.length <= 1000
          session[:utilization_rates_search_cache] = params[:search]
          #ids = @person_tasks.collect.map {|p| p.id}
          #session[:person_task_search_results] = ids
        else
          session[:utilization_rates_search_cache] = nil
          session[:utlization_rates_search_results] = nil
        end
        @total_count = @utilization_rates.length 
       #person_tasks = @person_tasks.collect

       @utilization_rates = @utilization_rates.paginate(:page => params[:page],:per_page => 100)    
      else
        # Nothing to search
        flash[:warning] = "You must enter something to search for" if request.post?
      end

      respond_to do |format|
        format.html {
            render :layout => 'application'
        }
      end   
   end  
end  

app/views/reports/_advance_search_tasks_form.html.erb
<%= form_for :search,:url => search_tasks_url,:html => {:method => 'post', :id => "basic_search", :class => "search" } do |f| %>
<fieldset>
	<%= hidden_field_tag :form_type," " ,:value => 'advance_form' %>
	<div class='pull-left'>
     <label>Shift Date</label>
     <div class="input-group date input-append">
       <%= f.text_field :minimum_date, :class => 'form-control' %><span class="add-on"><i class="icon-th"></i></span>
     </div>
   </div>
	<div class='pull-left' style='margin-top: 30px;margin-left:10px;font-size:11px !important'>
  	  <em>through</em>
   </div>
   <div class='pull-left' style='margin-left: 15px'>
     <label><br/></label>
     <div class="input-group date input-append">
       <%= f.text_field :maximum_date, :class => 'form-control' %><span class="add-on"><i class="icon-th"></i></span>
     </div>
	</div>
	<div class='pull-left' style='margin-left: 15px'>
	  <label>Employee Name</label>
	  <%= f.select(:person, Person.fetch_employees(current_user.organization,current_user.role,current_user.department).collect{|p| [p.first_name + " " + p.last_name, p.id] }, :include_blank => true) %>
	</div>
	<div class='pull-left' style='margin-left: 15px'>
	  <label>Primary Task</label>
	    <%= f.select(:task, Task.fetch_tasks(current_user.organization,current_user.role,current_user.department).collect{|t| [t.name, t.id] }, :include_blank => true) %>
	</div>
	<br/>	
	
	<div class='pull-left'>
	  <label>Specific Task</label>
	    <%= f.select(:specific_task, SpecificTask.fetch_specific_tasks(current_user.organization,current_user.role,current_user.department).collect{|t| [t.name, t.id] }, :include_blank => true) %>
	</div>
   
    <div class='pull-left' style='margin-left: 15px'>
	  <label>Department</label>
	    <%= f.select(:department, Department.departments(current_user.organization,current_user.role,current_user.department).collect{|t| [t.name, t.name] }, :include_blank => true) %>
	</div>
	
	<div class="pull-left" style='margin-left: 15px'>
	  <label>From or To</label>
	  <%= f.text_field :from_or_to %>
	</div>
	
	<div class="input-append pull-left" style='margin-left: 15px'>
	  <label>Note</label>
	  <%= f.text_field :note, :class => 'input-xlarge' %>
		  <%= f.submit "Search" , :class => 'btn btn-primary' %>
	</div><br/><br/>
	
	<div class=''>
	
	</div>	
 </fieldset><br/>

 <div id = 'advance_link' class='btn btn-danger'>show basic form</div>  
<% end %>

app/views/reports/_basic_search_tasks_form.html.erb
<%= form_for :search,:url => search_tasks_url,:html => {:method => 'post', :id => "basic_search", :class => "search" } do |f| %>
 <fieldset>
	
	<div style='width: 100%' class='pull-left'>

      <%= hidden_field_tag :form_type,"" ,:value => 'basic_form' %>
  	  <div class="input-append">
	    <%= f.text_field :keywords, :class=>"input-xxlarge" %>
	    <%= f.submit :Search , :class => 'btn' %> 
	  </div>
	 <span class="help-block" style='margin-top: -8px;font-size:11.5px'><em>search by task, specific task, person name, department, organization, note, from_or_to</em></span>
    </div>
  </fieldset><br/>

 <% if current_user.role.name == 'Administrator' || current_user.role.name == '1st Level User' %> 
   <div id = 'basic_link' class='btn btn-danger'>show advance form</div>  
 <% end %>
<% end %>

app/views/reports/_js.html.erb
<script>
   $(document).ready(function() {
	$('.input-group.date').datepicker({
	  format: "yyyy-mm-dd",
	  autoclose: true	
	});
	
	$('#basic_link').click(function(){
	  $('#basic').hide();
	  $('#advance').show();	
	 $(this).closest('form').find("input[type=text], textarea").val("");
	});
	
	$('#advance_link').click(function(){
	  $('#advance').hide();	 
	  $('#basic').show();	
	 $(this).closest('form').find("input[type=text], textarea").val("");
	});
	
	$("#utilization_rate_form select").change(function(){
      dataString = $("#utilization_rate_form").serialize();
	  $.ajax({
	    type: "GET",
		dataType: "script",
		url: "/utilization_rates",
		data: dataString,
		  beforeSend: function(data)
		  {
		    $('#spin_spin').show();
		  },
		  success: function(response)
		  {
		    $('#spin_spin').hide();	
		  }

	   });

	   return false;
    });
  });
</script>

app/views/reports/_search_rates_form.html.erb
<%= render partial: 'js' %>
<h4><font style='color:#000'>Search Rates</h4><br/>

	<%= form_for :search,:url => search_rates_url,:html => {:method => 'post', :id => "basic_search", :class => "search" } do |f| %>
		
		<fieldset>
		
			<div class='pull-left'>
		     <label>Shift Date</label>
		     <div class="input-group date input-append">
		       <%= f.text_field :minimum_date, :class => 'form-control' %><span class="add-on"><i class="icon-th"></i></span>
		     </div>
		   </div>
		
			<div class='pull-left' style='margin-top: 30px;margin-left:10px;font-size:11px !important'>
		  	  <em>through</em>
		   </div>
		
		   <div class='pull-left' style='margin-left: 15px'>
		     <label><br/></label>
		     <div class="input-group date input-append">
		       <%= f.text_field :maximum_date, :class => 'form-control' %><span class="add-on"><i class="icon-th"></i></span>
		     </div>
			</div>
			
			<div class='pull-left' style='margin-left: 15px'>
			  <label>Employee Name</label>
			  <%= f.select(:person, Person.fetch_employees(current_user.organization,current_user.role,current_user.department).collect{|p| [p.first_name + " " + p.last_name, p.id] }, :include_blank => true) %>
					  <%= f.submit "Search" , :class => 'btn btn-primary' %>
			</div>
		
			<br/>
		 </fieldset><br/>
<% end %>

app/views/reports/_search_rates_results.html.erb
<div id='utilization_rates'>
  <%= render partial: 'utilization_rates' %>
</div>

app/views/reports/_search_results.html.erb
<% if @person_tasks %>
<br/>
<h4>Search Results</h4>
<%="#{@total_count} records matched your search" %>
<br/><br/>

<div class='pull-right' style='margin-top:-60px'>
	
  <%= will_paginate @person_tasks %>
</div>
    <div  class='pull-right' style='margin-top: -80px;margin-right:10px'>
      <%= button_to 'Generate Spreadsheet', generate_spreadsheets_url, :class => 'btn btn-primary' if @total_count > 0 %>
	</div>
<table class="table table-striped" >
  <thead>
    <tr>
      <th width='10%'>Shift Date</th>
      <th>Person</th>
      <th  width='15%'>Primary Task</th>
      <th  width='15%'>Specific Task</th>
      <th width='9%'>Start Time</th>
      <th width='9%'>End Time</th>
      <th width='9%'>Total Time</th>
      <th  width='10%'>From or To</th>
	  <th width='10%'>Note</th>
	  <% if current_user.role.name == 'Administrator' || current_user.role.name == '1st Level User' %> 
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% for person_task in @person_tasks %>
    
       <% if person_task.is_submitted? %><tr class='warning'> <% end %>
	   <% if person_task.is_approved? %><tr class='success'> <% end %>
	   <% if person_task.is_disapproved? %><tr class='error'> <% end %>
		
		<td><%= person_task.start.strftime('%b. %e, %Y') if !person_task.start.nil? %></td>
		<td><%= person_task.person.first_name %></td>
        <td><%= person_task.task.name if !person_task.task_id.nil? %></td>
        <td><%= person_task.specific_task.name if !person_task.specific_task_id.nil? %></td>
        <td><%= person_task.start.strftime('%l:%M:%S %p') if !person_task.start.nil? %></td>
        <td><%= person_task.end.strftime('%l:%M:%S %p') if !person_task.end.nil? %></td>
		<td><%= person_task.total_time.strftime('%H:%M:%S') if !person_task.total_time.nil? %></td>
		<td><%= person_task.person_in_charge %></td>
		<td><%= person_task.note %></td>
		<% if current_user.role.name == 'Administrator' || current_user.role.name == '1st Level User' %> 
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_person_task_path(person_task), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      person_task_path(person_task),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<div class='pull-right' >
  <%= will_paginate @person_tasks %>
</div>

<% end %>

app/views/reports/_search_tasks_form.html.erb
<%= render partial: 'js' %>


	 <h4><font style='color:#000'>Search Activities</h3><br/>
	 
	 <% if session[:form_type].blank? %>
	    <% @style_basic = 'display:block' %>
	    <% @style_advance = 'display:none' %>
	 <% elsif session[:form_type] == 'basic_form'  %> 
	    <% @style_basic = 'display:block' %>
		<% @style_advance = 'display:none' %>
	
	 <% elsif session[:form_type] == 'advance_form'  %> 
	    <% @style_basic = 'display:none' %>
		<% @style_advance = 'display:block' %>
	 <% end %>
	
	 <div id='basic' style='<%= @style_basic %>'>	
       <%= render partial: 'basic_search_tasks_form' %>
     </div>
   <% if current_user.role.name == 'Administrator' || current_user.role.name == '1st Level User' %> 
     <div id='advance' style='<%= @style_advance %>'>
       <%= render partial: 'advance_search_tasks_form' %>
     </div>
   <% end %>

app/views/reports/_utilization_rates.html.erb
<% if @utilization_rates %>

<br/>

<div class='pull-right' style='margin-top:-80px;margin-right:-100px'>
  <%= will_paginate @utilization_rates %>
</div>

<table class="table table-striped" id='for_cbox'>
  <thead>
    <tr>

      <th width='10%'>Shift Date</th>
      <th>Employee</th>
      <th>Rate</th>
    </tr>
  </thead>
  <tbody>
    <% for rate in @utilization_rates %>
        <tr> 
		  <td><%= rate.shift_date.strftime('%b. %e, %Y') if !rate.shift_date.nil? %></td>
		  <td><%= rate.person.first_name + " "  + rate.person.last_name %></td>
		  <td><%= rate.total_utilization_rate %></td>
        </tr>
    <% end %>
  </tbody>
</table>
<div class='pull-right' >
  <%= will_paginate @utilization_rates %>
</div>

<% end %>

app/views/reports/_utilization_rates_report.html.erb
<% if @utilization_rates %>
<br/>
<h4>Search Results</h4>
<%="#{@total_count} records matched your search" %>
<br/><br/>

<div class='pull-right' style='margin-top:-60px'>
	
  <%= will_paginate @utilization_rates %>
</div>
    <div  class='pull-right' style='margin-top: -80px;margin-right:10px'>
      <%= button_to 'Generate Spreadsheet', generate_spreadsheets_url, :class => 'btn btn-primary' if @total_count > 0 %>
	</div>
<table class="table table-striped" >
  <thead>
    <tr>
      <th width='10%'>Shift Date</th>
      <th>Person</th>
      <th  width='15%'>Primary Task</th>
      <th  width='15%'>Specific Task</th>
      <th width='9%'>Start Time</th>
      <th width='9%'>End Time</th>
      <th width='9%'>Total Time</th>
      <th  width='10%'>From or To</th>
	  <th width='10%'>Note</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% for person_task in @utilization_rates %>
    
       <% if person_task.is_submitted? %><tr class='warning'> <% end %>
	   <% if person_task.is_approved? %><tr class='success'> <% end %>
	   <% if person_task.is_disapproved? %><tr class='error'> <% end %>
		
		<td><%= person_task.start.strftime('%b. %e, %Y') if !person_task.start.nil? %></td>
		<td><%= person_task.person.first_name %></td>
        <td><%= person_task.task.name if !person_task.task_id.nil? %></td>
        <td><%= person_task.specific_task.name if !person_task.specific_task_id.nil? %></td>
        <td><%= person_task.start.strftime('%l:%M:%S %p') if !person_task.start.nil? %></td>
        <td><%= person_task.end.strftime('%l:%M:%S %p') if !person_task.end.nil? %></td>
		<td><%= person_task.total_time.strftime('%H:%M:%S') if !person_task.total_time.nil? %></td>
		<td><%= person_task.person_in_charge %></td>
		<td><%= person_task.note %></td>
		
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_person_task_path(person_task), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      person_task_path(person_task),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
       
      </tr>
    <% end %>
  </tbody>
</table>

<div class='pull-right' >
  <%= will_paginate @utilization_rates %>
</div>

<% end %>

app/views/reports/generate_spreadsheets.js.erb
<%= flash_notice(flash.first[1], flash.first[0]) unless flash.blank? %>

app/views/reports/search_rates.html.erb
<div class="span12 body_layout">
  <div style='padding:20px'>
	<br/> 
	<div class="alert alert-info" style='width: 95% !important;'>	
      <%= render partial: 'search_rates_form' %>
    </div>
      <%= render partial: 'search_rates_results' %>
  </div>
</div>

app/views/reports/search_tasks.html.erb
<div class="span12 body_layout">
  <div style='padding:20px'>
	<br/> 
	<div class="alert alert-info" style='width: 95% !important;height: 300px !important'>	
      <%= render partial: 'search_tasks_form' %>
    </div>
      <%= render partial: 'search_results' %>
  </div>
</div>

app/views/reports/utilization_rates.html.erb
<%= render partial: 'js' %>

<div class="span12 body_layout" >
	<div class='own_page_header'>	
	   <h3>Utilization Rate</h3>
	   <div style='margin-top:-15px'>
	     <p>Productivity percentage<p>
		 <div id='count'>
 		   <%= render partial: 'rate_count' %>
	     </div>
	   </div>
	
	   <div id='spin_spin' class='pull-right' style='display:none;margin-top:-100px'>
	     <%= image_tag 'spin.gif' %>
	   </div>
	</div>
  <div style='padding:20px'>
	
  <br/>
	
	<%= form_tag utilization_rates_path, :method => 'get', :id => 'utilization_rate_form', :class => "form-search " do %><div class='pull-left' style='margin-left: 0px'>
	  <label>Employee Name</label>
	  <%= select_tag("person", options_from_collection_for_select(options_for_employees, :id, :first_name ,""), :include_blank => true) %>
	</div>   <% end %>
	<br/><br/>
	
	<div id='utilization_rates'>
	  <%= render partial: 'utilization_rates' %>
	</div>
	
  </div>
</div>

app/views/reports/utilization_rates.js.erb
$('#utilization_rates').html("<%= escape_javascript(render("utilization_rates")) %>");
$('#count').html("<%= escape_javascript(render("rate_count")) %>");